### ISSUE TITLE
Always giving unsuccessful requests 

### ISSUE THREAD

**Issue by jitijiti** [ckunakom/smule-song-list#1]
Hi,
I tried using it with my smule 2 users I have. It always giving
Unsuccessful Request T^T
for both of them.
Any updated code to circumvent this? appreciate it.

thanks.

**Comment by ckunakom** [comment]
Hey @jitijiti --thanks fo checking this out. Unfortunately I still couldn't figure out a way to work around this. I was actually trying to get the data the other day and the amount of time I can request shortened after that. Seems like each time you rerun the program, it will start counting against you.  Last time I was able to get data, I had to wait a week after the initial run, which I will try again next week. 

Did you get an 'Unsuccessful Request' right from the start or did you at least got a successful run one time and the rest has been unsuccessful?

**Comment by jitijiti** [comment]
thanks for the reply :) The return code is always seems to be non-200. Is there another way to "scrape" the smule or so? Basically I want to "search" and list the songs for my language (Kannada) e.g. Eventually I want to follow all the folks who have contributed songs in my language :)) if you some ideas, kindly share. Thanks

**Comment by ckunakom** [comment]
@jitijiti - sorry, this is the only way to get the data from smule from my research. Smule doesn't have an actual api page and judging from the 418 response code, I think they don't even care about making and maintaining this kind of data for public use. If you found another way, please share! 

Also, I was able to request the data this past weekend. It was like 5 days of not doing any requests and then I cleared cached before running the code (i don't think clearing cache would do anything but there's nothing to lose..) Hope you are able to get something afte giving the page a little break...

**Comment by ckunakom** [comment]
@jitijiti Hey there! I might be able to find you a solution!

Given how you told me that you never get a successful request, I am wondering if your IP address has something to do with it. I was able to do multiple requests with this solution: use **VPN**!! 

I use [protonVPN](https://protonvpn.com/) which is free. I do have to disconnect and re-connect to get a new IP address after each run, but this way you don't have to wait for weeks-months just to rerun the code. And this might solve the issue with your VPN (if that was an issue in the first place). 

I will be making the update to the repo to include this tip but also revamp the code a bit. Hopefully you can get the data you need from now on!
